### ISSUE TITLE
SLIP39

### ISSUE THREAD

**Issue by kirillkovalenko** [iancoleman/shamir39#17]
Now that we have [SLIP39](https://github.com/satoshilabs/slips/blob/master/slip-0039.md) live including a [JavaScript library](https://github.com/ilap/slip39-js), do you have any plans to switch this project to it?

**Comment by iancoleman** [comment]
No, I hope to find time to build a different (but similar) slip39 tool and wouldn't integrate into this one since the protocols are very different and incompatible so probably quite misleading to put them in the same tool.
