### ISSUE TITLE
20 word shares

### ISSUE THREAD

**Issue by intek71** [iancoleman/shamir39#23]
Hi, would it be possible to split/recombine into 20 word shares:
Trezor T and Keystome offer Shamir backup options, where they split into n/m shares of 20 words. And they are compatible. Still, my concerb is if both trzor and Keystone stop working, I would not be able to recover from my Shamir 20 word share they generate. I am wondering if you could adjust the number of words per share into 20 and that way I would be able to software recombine them if needed. Thank you in advance

**Comment by iancoleman** [comment]
I think those hardware wallets use slip39, not shamir39

If you use https://iancoleman.io/slip39/ with 128 bits of entropy it creates shares of 20 words

You should be able to recover from 20-word-shares with any slip39 compatible wallet

**Comment by intek71** [comment]
Thank you. Got it. From what I understand, from the 3/5 20 word shards there is no way to recreate a 24 word seed to use in a bip39 wallet? Needs to be done through importing the master key?

**Comment by iancoleman** [comment]
No the shards cannot be used to create a 24 word bip39 seed

More info in this part of the slip39 spec:
https://github.com/satoshilabs/slips/blob/master/slip-0039.md#user-content-bip39compatibility

**Comment by intek71** [comment]
Thank you very much and sorry for silly questions.
