### ISSUE TITLE
amused index number

### ISSUE THREAD

**Issue by phyzpp** [iancoleman/shamir39#6]
In the draft, you wrote

'amused' is index 65 in the English wordlist. 

However, "amused" has an index number 66 in the below list:

https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

Maybe not that important but can be fixed.

**Comment by iancoleman** [comment]
The list starts with line 1, so 'amused' is *line* 66 but is *index* 65 since indexes start at 0.

Thanks for the attention to detail anyhow!
